services:
  devhabit.api:
    image: ${DOCKER_REGISTRY-}devhabitapi
    build:
      context: .
      dockerfile: DevHabit.API/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      # Seq
      # place where we sending telemetry data (local)
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.seq:5341/ingest/otlp # dockert net
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf # internal port who accepting telemetry data
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc

  devhabit.postgres:
    image: postgres:17.2
    environment:
        POSTGRES_DB: devhabit
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432 # host port : docker port

  devhabit.seq:
    image: datalust/seq:2024.3
    environment:
        ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341
  
  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
        DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888